Repository Rocket-Eagle/Rocket-Eagle, pull requests merged in 2021-03, with the labels that each got.

#110 Adding the breakdown
  README.md
Labels: documentation

#111 Fixed Ending Screen Buttons
  rocket_eagle/Assets/Art/SubMenu/TEMPbridCoinLogo.png
  rocket_eagle/Assets/Art/SubMenu/TEMPbridCoinLogo.png.meta
  rocket_eagle/Assets/LapCounter.cs
  rocket_eagle/Assets/Prefabs/BirdCoinCount.prefab
  rocket_eagle/Assets/Prefabs/BirdCoinCount.prefab.meta
  rocket_eagle/Assets/Resources/Skins.meta
  rocket_eagle/Assets/Resources/Skins/bird.png
  rocket_eagle/Assets/Resources/Skins/bird.png.meta
  rocket_eagle/Assets/Resources/Skins/blueBird.png
  rocket_eagle/Assets/Resources/Skins/blueBird.png.meta
  rocket_eagle/Assets/Resources/Skins/fireBird.png
  rocket_eagle/Assets/Resources/Skins/fireBird.png.meta
  rocket_eagle/Assets/Scene.unity
  rocket_eagle/Assets/Scenes/FinishSceneSP.unity
  rocket_eagle/Assets/Scenes/FinishSceneSP.unity.meta
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/Assets/Scenes/SinglePlayerEnding.unity
  rocket_eagle/Assets/Scripts/BirdController.cs
  rocket_eagle/Assets/Scripts/MenuButtonController.cs
  rocket_eagle/Assets/Scripts/PurchaseSkin.cs
  rocket_eagle/Assets/Scripts/PurchaseSkin.cs.meta
  rocket_eagle/Assets/Scripts/SaveGameData.cs
  rocket_eagle/Assets/Scripts/SaveGameData.cs.meta
  rocket_eagle/Assets/Scripts/SelectLevel.cs
  rocket_eagle/Assets/Scripts/SkinData.cs
  rocket_eagle/Assets/Scripts/SkinData.cs.meta
  rocket_eagle/Assets/Scripts/Skins.cs
  rocket_eagle/Assets/Scripts/Skins.cs.meta
  rocket_eagle/ProjectSettings/EditorBuildSettings.asset
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Low Priority, Menu System, task

#117 Can change the bird's sprite.
  rocket_eagle/Assets/Art/Bird Skins.meta
  rocket_eagle/Assets/Art/Bird Skins/bird.png
  rocket_eagle/Assets/Art/Bird Skins/bird.png.meta
  rocket_eagle/Assets/Art/Level Assets.meta
  rocket_eagle/Assets/Art/Level Assets/arrow.png
  rocket_eagle/Assets/Art/Level Assets/arrow.png.meta
  rocket_eagle/Assets/Art/Level Assets/field.meta
  rocket_eagle/Assets/Art/Level Assets/field/fieldBackground.png
  rocket_eagle/Assets/Art/Level Assets/field/fieldBackground.png.meta
  rocket_eagle/Assets/Art/Level Assets/field/finishFlag.png
  rocket_eagle/Assets/Art/Level Assets/field/finishFlag.png.meta
  rocket_eagle/Assets/Art/Level Assets/field/pipe.png
  rocket_eagle/Assets/Art/Level Assets/field/pipe.png.meta
  rocket_eagle/Assets/Scenes/Field.unity
  rocket_eagle/Assets/Scripts/BirdController.cs
Labels: Cosmetics, Low Priority

#122 Adding Currency and Skin Customization
  rocket_eagle/Assets/Art/Bird Skins.meta
  rocket_eagle/Assets/Art/Bird Skins/bird.png
  rocket_eagle/Assets/Art/Bird Skins/bird.png.meta
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/Assets/Scripts/BirdController.cs
  rocket_eagle/Assets/Scripts/PurchaseSkin.cs
  rocket_eagle/Assets/Scripts/SaveGameData.cs
  rocket_eagle/Assets/Scripts/SkinData.cs
  rocket_eagle/Assets/Scripts/Skins.cs
  rocket_eagle/Assets/Tests/EditMode/SavingTest.cs
  rocket_eagle/Assets/Tests/EditMode/SavingTest.cs.meta
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Cosmetics, Currency, Feature, Medium Priority, Menu System

#124 Made a way to add BirdCoin
  rocket_eagle/Assets/Scripts/PurchaseSkin.cs
  rocket_eagle/Assets/Scripts/SaveGameData.cs
  rocket_eagle/Assets/Tests/EditMode/SavingTest.cs
Labels: Currency, Unit Testing

#126 Added way to make Birdcoin
  rocket_eagle/Assets/Art/SubMenu/TEMPbridCoinLogo.png
  rocket_eagle/Assets/Art/SubMenu/bcLogo.png
  rocket_eagle/Assets/Art/SubMenu/bcLogo.png.meta
  rocket_eagle/Assets/Images.meta
  rocket_eagle/Assets/Mirror/Timer.cs
  rocket_eagle/Assets/Prefabs/BirdCoinCount.prefab
  rocket_eagle/Assets/Prefabs/New Folder.meta
  rocket_eagle/Assets/Scenes/FinishSceneSP.unity
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/Assets/Scripts/FinishButtons.cs
  rocket_eagle/Assets/Scripts/FinishScene.cs
  rocket_eagle/Assets/Scripts/FinishScene.cs.meta
  rocket_eagle/Assets/Scripts/PurchaseSkin.cs
  rocket_eagle/Assets/Scripts/SaveGameData.cs
  rocket_eagle/ProjectSettings/ProjectSettings.asset
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Currency, Medium Priority

#130 Added loading lobby players into a game map.
  rocket_eagle/Assets/Mirror/NetworkGamePlayerLobby.cs
  rocket_eagle/Assets/Mirror/NetworkGamePlayerLobby.cs.meta
  rocket_eagle/Assets/Mirror/NetworkManagerLobby.cs
  rocket_eagle/Assets/Mirror/NetworkRoomPlayerLobby.cs
  rocket_eagle/Assets/Mirror/Resources/SpawnablePrefabs/GamePlayer.prefab
  rocket_eagle/Assets/Mirror/Resources/SpawnablePrefabs/GamePlayer.prefab.meta
  rocket_eagle/Assets/Mirror/Resources/SpawnablePrefabs/RoomPlayer.prefab
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/rocket_eagle_Data/Managed/Assembly-CSharp.dll
  rocket_eagle/rocket_eagle_Data/globalgamemanagers
  rocket_eagle/rocket_eagle_Data/globalgamemanagers.assets
  rocket_eagle/rocket_eagle_Data/level0
  rocket_eagle/rocket_eagle_Data/level1
  rocket_eagle/rocket_eagle_Data/level2
  rocket_eagle/rocket_eagle_Data/level3
  rocket_eagle/rocket_eagle_Data/resources.assets
  rocket_eagle/rocket_eagle_Data/sharedassets0.assets
  rocket_eagle/rocket_eagle_Data/sharedassets1.assets
  rocket_eagle/rocket_eagle_Data/sharedassets2.assets
  rocket_eagle/rocket_eagle_Data/sharedassets3.assets
Labels: Basic Game Mechanics, Feature, High Priority, Multiplayer

#131 Added Countdown to Multiplayer
  rocket_eagle/Assets/Mirror/BirdController.cs
  rocket_eagle/Assets/Mirror/CountDown.cs
  rocket_eagle/Assets/Mirror/CountDown.cs.meta
  rocket_eagle/Assets/Scenes/Field.unity
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Basic Game Mechanics, High Priority, Multiplayer, task

#129 ReAdded Single Player
  rocket_eagle/Assets/Prefabs/singlebird.prefab
  rocket_eagle/Assets/Prefabs/singlebird.prefab.meta
  rocket_eagle/Assets/Scenes/SingleField.unity
  rocket_eagle/Assets/Scenes/SingleField.unity.meta
  rocket_eagle/Assets/Scripts/SceneLoading.cs
  rocket_eagle/Assets/Scripts/SinglePlayer.meta
  rocket_eagle/Assets/Scripts/SinglePlayer/SingleBirdController.cs
  rocket_eagle/Assets/Scripts/SinglePlayer/SingleBirdController.cs.meta
  rocket_eagle/Assets/Scripts/SinglePlayer/SingleCameraControl.cs
  rocket_eagle/Assets/Scripts/SinglePlayer/SingleCameraControl.cs.meta
  rocket_eagle/Assets/Scripts/SinglePlayer/SingleLapCount.cs
  rocket_eagle/Assets/Scripts/SinglePlayer/SingleLapCount.cs.meta
  rocket_eagle/Assets/Scripts/SinglePlayer/SinglePlayerController.cs
  rocket_eagle/Assets/Scripts/SinglePlayer/SinglePlayerController.cs.meta
  rocket_eagle/Assets/Scripts/SinglePlayer/SingleTimer.cs
  rocket_eagle/Assets/Scripts/SinglePlayer/SingleTimer.cs.meta
  rocket_eagle/ProjectSettings/EditorBuildSettings.asset
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Basic Game Mechanics, High Priority, bug

#135 Fixed Birdcoin not adding coin
  rocket_eagle/Assets/Mirror/Timer.cs
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/Assets/Scripts/MenuButtonController.cs
  rocket_eagle/Assets/Scripts/SaveGameData.cs
  rocket_eagle/Assets/Scripts/SinglePlayer/SingleTimer.cs
Labels: Bug Fix, Currency, Medium Priority

#137 Fixed increased Birdcoin issue
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/Assets/Scripts/MenuButtonController.cs
  rocket_eagle/Assets/Scripts/SinglePlayer/SingleTimer.cs
Labels: Bug Fix, Currency, Medium Priority

#139 Finished fixing a bug about BirdCoin not adding properly
  rocket_eagle/Assets/Mirror/Timer.cs
Labels: Bug Fix, Currency, Medium Priority, Multiplayer

#138 Enter multiplayer from lobby
  rocket_eagle/Assets/Prefabs/bird.prefab
  rocket_eagle/Assets/Scenes/Field.unity
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: High Priority, Multiplayer

#141 Display the cost of the skins to the user
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/Assets/Scripts/PurchaseSkin.cs
Labels: Cosmetics, Low Priority, Menu System, task

#143 Updating new maps to work with new code
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  .github/ISSUE_TEMPLATE/user-story.md
  Diagram/Block Diagram.jpg
  Diagram/Class Diagram.jpg
  Diagram/Sequence Diagrams/Adding Sound.jpg
  Diagram/Sequence Diagrams/Change Settings.jpg
  Diagram/Sequence Diagrams/Get Into The Game.jpg
  Diagram/Sequence Diagrams/Move The Player.jpg
  Diagram/Sequence Diagrams/See Finishing Time.jpg
  Diagram/Sequence Diagrams/Speed Boost.jpg
  README.md
  rocket_eagle/Assets/Art/Level Assets/field/caveBackground.png
  rocket_eagle/Assets/Art/Level Assets/field/caveBackground.png.meta
  rocket_eagle/Assets/Art/Level Assets/field/jellyfish.png
  rocket_eagle/Assets/Art/Level Assets/field/jellyfish.png.meta
  rocket_eagle/Assets/Art/Level Assets/field/oceanBackground.png
  rocket_eagle/Assets/Art/Level Assets/field/oceanBackground.png.meta
  rocket_eagle/Assets/Art/Level Assets/field/stonePillar.png
  rocket_eagle/Assets/Art/Level Assets/field/stonePillar.png.meta
  rocket_eagle/Assets/Prefabs/empty.prefab
  rocket_eagle/Assets/Prefabs/empty.prefab.meta
  rocket_eagle/Assets/Scenes/Cave.unity
  rocket_eagle/Assets/Scenes/Cave.unity.meta
  rocket_eagle/Assets/Scenes/Ocean.unity
  rocket_eagle/Assets/Scenes/Ocean.unity.meta
  rocket_eagle/Assets/Tests/PlayMode/SampleTest.cs
  rocket_eagle/Assets/Tests/PlayMode/SampleTest.cs.meta
  rocket_eagle/Library/nothing
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Level Design

#145 Default skins
  rocket_eagle/Assets/Mirror/BirdController.cs
  rocket_eagle/Assets/Scenes/SingleField.unity
  rocket_eagle/Assets/Scripts/FinishScene.cs
  rocket_eagle/Assets/Scripts/MenuButtonController.cs
  rocket_eagle/Assets/Scripts/PurchaseSkin.cs
  rocket_eagle/Assets/Scripts/SaveGameData.cs
  rocket_eagle/Assets/Scripts/SinglePlayer/SinglePlayerController.cs
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Cosmetics, Low Priority

#146 Level Selection
  rocket_eagle/Assets/Prefabs/bird.prefab
  rocket_eagle/Assets/Resources/LevelSelection/Levels/Cave.png
  rocket_eagle/Assets/Resources/LevelSelection/Levels/Cave.png.meta
  rocket_eagle/Assets/Resources/LevelSelection/Levels/Ocean.png
  rocket_eagle/Assets/Resources/LevelSelection/Levels/Ocean.png.meta
  rocket_eagle/Assets/Resources/LevelSelection/Levels/Sample2LevelSelectionImage.png
  rocket_eagle/Assets/Resources/LevelSelection/Levels/SingleField.PNG
  rocket_eagle/Assets/Resources/LevelSelection/Levels/SingleField.PNG.meta
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/Assets/Scripts/FinishScene.cs
  rocket_eagle/Assets/Scripts/PurchaseSkin.cs
  rocket_eagle/Assets/Scripts/SceneLoading.cs
  rocket_eagle/Assets/Scripts/SelectLevel.cs
Labels: Basic Game Mechanics, High Priority, Menu System

#151 Finished Level Selection
  rocket_eagle/Assets/Scenes/FinishSceneSP.unity
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/Assets/Scripts/FinishScene.cs
  rocket_eagle/Assets/Scripts/MenuButtonController.cs
  rocket_eagle/Assets/Scripts/PurchaseSkin.cs
  rocket_eagle/ProjectSettings/EditorBuildSettings.asset
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Cosmetics, High Priority, Menu System, task

#153 Adding Tests
  rocket_eagle/Assets/Scripts/SaveGameData.cs
  rocket_eagle/Assets/Tests/EditMode/SavingTest.cs
  rocket_eagle/Assets/Tests/EditMode/SkinDataTest.cs
  rocket_eagle/Assets/Tests/EditMode/SkinDataTest.cs.meta
  rocket_eagle/Assets/Tests/EditMode/TestTest.cs
  rocket_eagle/Assets/Tests/EditMode/TestTest.cs.meta
  rocket_eagle/Assets/Tests/PlayMode.meta
  rocket_eagle/Assets/Tests/PlayMode/SampleTest.cs
Labels: Medium Priority, Unit Testing, task

#154 Added canvas to new maps
  rocket_eagle/Assets/Scenes/Cave.unity
  rocket_eagle/Assets/Scenes/Ocean.unity
Labels: Level Design
