Repository Rocket-Eagle/Rocket-Eagle, pull requests merged in 2021-04, with the labels that each got.

#160 Kory items
  rocket_eagle/Assets/Art/Items.meta
  rocket_eagle/Assets/Art/Items/Gas.png
  rocket_eagle/Assets/Art/Items/Gas.png.meta
  rocket_eagle/Assets/Art/Items/Ghost.png
  rocket_eagle/Assets/Art/Items/Ghost.png.meta
  rocket_eagle/Assets/Art/Items/Inventory.png
  rocket_eagle/Assets/Art/Items/Inventory.png.meta
  rocket_eagle/Assets/Art/Items/ItemCrate.png
  rocket_eagle/Assets/Art/Items/ItemCrate.png.meta
  rocket_eagle/Assets/Art/Items/Restart.png
  rocket_eagle/Assets/Art/Items/Restart.png.meta
  rocket_eagle/Assets/Scenes/SingleField.unity
  rocket_eagle/Assets/Scripts/SinglePlayer/BirdItem.cs
  rocket_eagle/Assets/Scripts/SinglePlayer/BirdItem.cs.meta
  rocket_eagle/Assets/Scripts/SinglePlayer/Gas.asset
  rocket_eagle/Assets/Scripts/SinglePlayer/Gas.asset.meta
  rocket_eagle/Assets/Scripts/SinglePlayer/Ghost.asset
  rocket_eagle/Assets/Scripts/SinglePlayer/Ghost.asset.meta
  rocket_eagle/Assets/Scripts/SinglePlayer/Item.cs
  rocket_eagle/Assets/Scripts/SinglePlayer/Item.cs.meta
  rocket_eagle/Assets/Scripts/SinglePlayer/ItemBlock.cs
  rocket_eagle/Assets/Scripts/SinglePlayer/ItemBlock.cs.meta
  rocket_eagle/Assets/Scripts/SinglePlayer/ItemHandler.cs
  rocket_eagle/Assets/Scripts/SinglePlayer/ItemHandler.cs.meta
  rocket_eagle/Assets/Scripts/SinglePlayer/ItemUIHandle.cs
  rocket_eagle/Assets/Scripts/SinglePlayer/ItemUIHandle.cs.meta
  rocket_eagle/Assets/Scripts/SinglePlayer/Restart.asset
  rocket_eagle/Assets/Scripts/SinglePlayer/Restart.asset.meta
  rocket_eagle/Assets/Scripts/SinglePlayer/SinglePlayerController.cs
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Items, Medium Priority, task

#163 Sounds for Cave and Ocean Items
  rocket_eagle/Assets/Scenes/Cave.unity
  rocket_eagle/Assets/Scenes/Ocean.unity
Labels: Medium Priority, Sounds, task

#164 Added sound on Multi Field
  rocket_eagle/Assets/Scenes/Field.unity
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Medium Priority, Sounds

#173 Added skin
  rocket_eagle/Assets/Resources/Skins/blingBird.png
  rocket_eagle/Assets/Resources/Skins/blingBird.png.meta
  rocket_eagle/Assets/Scripts/PurchaseSkin.cs
Labels: Cosmetics, Low Priority, task
