Repository Rocket-Eagle/Rocket-Eagle, pull requests merged in 2021-02, with the labels that each got.

#61 Update BirdController.cs
  rocket_eagle/Assets/Scripts/BirdController.cs
Labels: Basic Game Mechanics

#65 Sprint 2 Menu System
  rocket_eagle/Assets/Resources.meta
  rocket_eagle/Assets/Resources/LevelSelection.meta
  rocket_eagle/Assets/Resources/LevelSelection/LeftButton.png
  rocket_eagle/Assets/Resources/LevelSelection/LeftButton.png.meta
  rocket_eagle/Assets/Resources/LevelSelection/Levels.meta
  rocket_eagle/Assets/Resources/LevelSelection/Levels/Sample2LevelSelectionImage.png
  rocket_eagle/Assets/Resources/LevelSelection/Levels/Sample2LevelSelectionImage.png.meta
  rocket_eagle/Assets/Resources/LevelSelection/Levels/SampleLevelSelectionImage.PNG
  rocket_eagle/Assets/Resources/LevelSelection/Levels/SampleLevelSelectionImage.PNG.meta
  rocket_eagle/Assets/Resources/LevelSelection/RightButton.png
  rocket_eagle/Assets/Resources/LevelSelection/RightButton.png.meta
  rocket_eagle/Assets/Scenes/LoadingScreen.unity
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/Assets/Scripts/MenuButtonController.cs
  rocket_eagle/Assets/Scripts/SelectLevel.cs
  rocket_eagle/Assets/Scripts/SelectLevel.cs.meta
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Medium Priority, Menu System, User Stories

#67 Mccarko field map
  rocket_eagle/Assets/Images.meta
  rocket_eagle/Assets/Images/fieldBackground.png
  rocket_eagle/Assets/Images/fieldBackground.png.meta
  rocket_eagle/Assets/Images/finishFlag.png
  rocket_eagle/Assets/Images/finishFlag.png.meta
  rocket_eagle/Assets/Images/pipe.png
  rocket_eagle/Assets/Images/pipe.png.meta
  rocket_eagle/Assets/Scenes/Field.unity
  rocket_eagle/Assets/Scenes/Field.unity.meta
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: High Priority, Level Design

#69 Added grading instruction
  README.md
Labels: documentation

#68 Mccarko field map
  rocket_eagle/Assets/Images.meta
  rocket_eagle/Assets/Images/fieldBackground.png
  rocket_eagle/Assets/Images/fieldBackground.png.meta
  rocket_eagle/Assets/Images/finishFlag.png
  rocket_eagle/Assets/Images/finishFlag.png.meta
  rocket_eagle/Assets/Images/pipe.png
  rocket_eagle/Assets/Images/pipe.png.meta
  rocket_eagle/Assets/Scenes/Field.unity
  rocket_eagle/Assets/Scenes/Field.unity.meta
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Level Design, Medium Priority

#70 Added Volume Control
  rocket_eagle/Assets/Art/LoadingScreen/LoadingPipe.png
  rocket_eagle/Assets/Art/LoadingScreen/LoadingPipe.png.meta
  rocket_eagle/Assets/Scenes/Field.unity
  rocket_eagle/Assets/Scenes/LoadingScreen.unity
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/Assets/Scripts/MenuButtonController.cs
  rocket_eagle/Assets/Scripts/OptionsMenu.cs
  rocket_eagle/Assets/Scripts/OptionsMenu.cs.meta
  rocket_eagle/Assets/Scripts/SceneLoading.cs
  rocket_eagle/Assets/Scripts/SelectLevel.cs
  rocket_eagle/Assets/Sounds/Mixer.meta
  rocket_eagle/Assets/Sounds/Mixer/MainMixer.mixer
  rocket_eagle/Assets/Sounds/Mixer/MainMixer.mixer.meta
  rocket_eagle/ProjectSettings/EditorBuildSettings.asset
  rocket_eagle/ProjectSettings/ProjectSettings.asset
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Low Priority, Menu System, task

#71 Completed single player functionality
  rocket_eagle/Assets/Images/arrow.png
  rocket_eagle/Assets/Images/arrow.png.meta
  rocket_eagle/Assets/Images/bird.png
  rocket_eagle/Assets/Images/bird.png.meta
  rocket_eagle/Assets/Scenes/Field.unity
  rocket_eagle/Assets/Scenes/SinglePlayerEnding.unity
  rocket_eagle/Assets/Scenes/SinglePlayerEnding.unity.meta
  rocket_eagle/Assets/Scripts/BirdController.cs
  rocket_eagle/Assets/Scripts/CameraControl.cs
  rocket_eagle/Assets/Scripts/CameraControl.cs.meta
  rocket_eagle/Assets/Scripts/FinishButtons.cs
  rocket_eagle/Assets/Scripts/FinishButtons.cs.meta
  rocket_eagle/Assets/Scripts/Timer.cs
  rocket_eagle/ProjectSettings/EditorBuildSettings.asset
  rocket_eagle/ProjectSettings/TagManager.asset
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Basic Game Mechanics, High Priority, Menu System

#73 Small refactoring
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/Assets/Scripts/MenuButtonController.cs
  rocket_eagle/Assets/Sounds/FX/Menu/SelectSound.mp3
  rocket_eagle/Assets/Sounds/FX/Menu/SelectSound.mp3.meta
  rocket_eagle/Assets/Sounds/FX/Menu/backSound.mp3
  rocket_eagle/Assets/Sounds/FX/Menu/backSound.mp3.meta
  rocket_eagle/ProjectSettings/EditorBuildSettings.asset
Labels: Low Priority, Menu System

#74 Adding CI
  rocket_eagle/Assets/Editor.meta
  rocket_eagle/Assets/Editor/BuildCommand.cs
  rocket_eagle/Assets/Editor/BuildCommand.cs.meta
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Unit Testing

#76 Possible CI integration
  rocket_eagle/.github/Unity_v2020.x.ulf.enc
  rocket_eagle/.github/workflows/main.yml
Labels: documentation

#77 Possible CI integration
  rocket_eagle/.github/Unity_v2020.x.ulf.enc
  rocket_eagle/.github/workflows/main.yml
Labels: documentation

#78 Attempt 2 at CI
  .gitignore
  README.md
Labels: documentation

#79 Fixed extra bullet point
  README.md
Labels: documentation

#87 Add files via upload
  Diagram/Block Diagram.jpg
  Diagram/Class Diagram.jpg
  Diagram/Sequence Diagrams/Adding Sound.jpg
  Diagram/Sequence Diagrams/Change Settings.jpg
  Diagram/Sequence Diagrams/Get Into The Game.jpg
  Diagram/Sequence Diagrams/Move The Player.jpg
  Diagram/Sequence Diagrams/See Finishing Time.jpg
  Diagram/Sequence Diagrams/Speed Boost.jpg
Labels: documentation

#88 Added Testing Basics
  rocket_eagle/.github/workflows/activation.yml
  rocket_eagle/.github/workflows/main.yml
  rocket_eagle/Assets/Scripts/Scripts.asmdef
  rocket_eagle/Assets/Scripts/Scripts.asmdef.meta
  rocket_eagle/Assets/Tests.meta
  rocket_eagle/Assets/Tests/EditMode.meta
  rocket_eagle/Assets/Tests/EditMode/EditMode.asmdef
  rocket_eagle/Assets/Tests/EditMode/EditMode.asmdef.meta
  rocket_eagle/Assets/Tests/EditMode/TestTest.cs
  rocket_eagle/Assets/Tests/EditMode/TestTest.cs.meta
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Unit Testing

#89 Removed old CI stuff
  rocket_eagle/.github/Unity_v2020.x.ulf.enc
  rocket_eagle/.github/workflows/activation.yml
  rocket_eagle/.github/workflows/main.yml
Labels: documentation

#90 Adding the testing basics
  rocket_eagle/.github/Unity_v2020.x.ulf.enc
  rocket_eagle/.github/workflows/main.yml
  rocket_eagle/Assets/Scripts/Scripts.asmdef
  rocket_eagle/Assets/Scripts/Scripts.asmdef.meta
  rocket_eagle/Assets/Tests.meta
  rocket_eagle/Assets/Tests/EditMode.meta
  rocket_eagle/Assets/Tests/EditMode/EditMode.asmdef
  rocket_eagle/Assets/Tests/EditMode/EditMode.asmdef.meta
  rocket_eagle/Assets/Tests/EditMode/TestTest.cs
  rocket_eagle/Assets/Tests/EditMode/TestTest.cs.meta
  rocket_eagle/UserSettings/EditorUserSettings.asset
Labels: Unit Testing, documentation

#92 Adding exit button
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/Assets/Scripts/CameraControl.cs
  rocket_eagle/Assets/Scripts/MenuButtonController.cs
  rocket_eagle/Assets/Tests/PlayMode.meta
  rocket_eagle/ProjectSettings/EditorBuildSettings.asset
Labels: Basic Game Mechanics, Bug Fix, Menu System

#93 Added the exit button on menu screen
  rocket_eagle/Assets/Scenes/MainMenu.unity
  rocket_eagle/Assets/Scripts/CameraControl.cs
  rocket_eagle/Assets/Scripts/MenuButtonController.cs
  rocket_eagle/Assets/Tests/PlayMode.meta
  rocket_eagle/ProjectSettings/EditorBuildSettings.asset
Labels: Basic Game Mechanics, Bug Fix, High Priority, Menu System
